server:
  port: 8081

spring:
  profiles:
    active: dev # Varsayılan profil
  application:
    name: codeyzerflix-api

logging:
  level:
    root: INFO
    com.codeyzerflix: DEBUG
    org.springframework.web: INFO
