version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: codeyzerflix-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=codeyzerflix
    volumes:
      - mongodb_data:/data/db
    networks:
      - codeyzerflix-network

  mongo-express:
    image: mongo-express:latest
    container_name: codeyzerflix-mongo-express
    restart: always
    ports:
      - "8082:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_URL=mongodb://admin:password@mongodb:27017/
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=password
    depends_on:
      - mongodb
    networks:
      - codeyzerflix-network

volumes:
  mongodb_data:

networks:
  codeyzerflix-network:
    driver: bridge 