spring:
  data:
    mongodb:
      uri: mongodb://admin:password@mongodb:27017/codeyzerflix?authSource=admin
      database: codeyzerflix
      auto-index-creation: true

codeyzerflix-common:
  cors:
    allowed-origins:
      - https://flix.codeyzer.com
    allowed-methods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
    allowed-headers:
      - Authorization
      - Content-Type
      - Accept
      - Origin
      - X-Requested-With
    allow-credentials: true
    max-age: 3600