codeyzerflix-common:
  cors:
    allowed-origins:
      - https://codeyzerflix.tail9fb8f4.ts.net
    allowed-methods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
    allowed-headers:
      - Authorization
      - Content-Type
      - Accept
      - Origin
      - X-Requested-With
    allow-credentials: true
    max-age: 3600